[paths]
output = "declengine"
source = [".", "Polyweb", "Polyweb/Polynet"]
artifact = "obj"

[options]
compilation-flags = "-Wall -std=c++17 -O3 -pthread"
libraries = ["ssl", "crypto"]
preludes = ["cd whitakers-words && $(MAKE)"]
clean-preludes = ["cd whitakers-words && $(MAKE) clean"]

[env.OS.Windows_NT.options]
libraries = ["ssl", "crypto", "ws2_32"]
